// src/configs/colDefs.js

export const colDefs = [
  {
    headerCheckboxSelection: true,
    checkboxSelection: true,
    width: 100,
  },
  {
    field: "noKewajiban",
    headerName: "No. Kewajiban",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "noPolisi",
    headerName: "No. Polisi",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "pemiliki",
    headerName: "Pemiliki",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "peserta",
    headerName: "Peserta",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "nomorVA",
    headerName: "Nomor VA",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "hargaTerbentuk",
    headerName: "Harga Terbentuk (Rp)",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "biayaAdmin",
    headerName: "Biaya Admin ex PPN (Rp)",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "ppn",
    headerName: "PPN (Rp)",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "total",
    headerName: "Total (Rp)",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "tanggalLelang",
    headerName: "Tanggal Lelang",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "tanggalJatuhTempo",
    headerName: "Tanggal Jatuh Tempo",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "tanggalLunas",
    headerName: "Tanggal Lunas",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
  {
    field: "status",
    headerName: "Status",
    filter: true,
    floatingFilter: true,
    headerClass: "text-center",
  },
];
